par("mar" = c(5.1, 5.1, 4.1, 2.1))
data <- read.csv("data.txt", header=TRUE, sep=";")
data$DateTime <- strptime(paste(data$Date, data$Time, sep  = " "), "%d/%m/%Y %H:%M:%S")
plot(data$DateTime, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(data$DateTime, data$Sub_metering_2, type="l", col="red")
lines(data$DateTime, data$Sub_metering_3, type="l", col="blue")
legend("topright", lwd = 2, cex=0.84,  col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png") 
dev.off()