png(file = "plot4.png") 
data <- read.csv("data.txt", header=TRUE, sep=";")
data$DateTime <- strptime(paste(data$Date, data$Time, sep  = " "), "%d/%m/%Y %H:%M:%S")
par("mfrow" = c(2,2))
plot(data$DateTime, data$Global_active_power, type="l", xlab = "", ylab="Global Active Power")
plot(data$DateTime, data$Voltage, type="l", xlab = "datetime", ylab="Voltage")
plot(data$DateTime, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(data$DateTime, data$Sub_metering_2, type="l", col="red")
lines(data$DateTime, data$Sub_metering_3, type="l", col="blue")
legend("topright", lwd = 2, col=c("black", "red", "blue"), bty="n", cex= 0.84, legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data$DateTime, data$Global_reactive_power, type="l", xlab = "datetime", ylab="Global_reactive_power")
dev.off()